style: keepachangelog
template: CHANGELOG.md
info:
  title: CHANGELOG
  repository_url: https://github.com/Mug1vara97/mug1vara97.github.io
options:
  commits:
    filters:
      Type: 
        - feat
        - fix
        - perf
        - refactor
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring